services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    command: "/opt/bitnami/spark/sbin/start-master.sh"
    networks:
      - my-shared-network
      - spark-network
    hostname: spark-master
    volumes:
      - shared-jars:/shared-jars

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
      - init-jars
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: "/opt/bitnami/spark/sbin/start-worker.sh spark://spark-master:7077"
    networks:
      - my-shared-network
      - spark-network
    hostname: spark-worker-1
    volumes:
      - shared-jars:/shared-jars

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    depends_on:
      - spark-master
      - init-jars
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: "/opt/bitnami/spark/sbin/start-worker.sh spark://spark-master:7077"
    networks:
      - my-shared-network
      - spark-network
    hostname: spark-worker-2
    volumes:
      - shared-jars:/shared-jars

  pyspark:
    build: .
    container_name: pyspark-container
    depends_on:
      - spark-master
      - init-jars
    environment:
      - SPARK_MASTER=${SPARK_MASTER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    networks:
      - my-shared-network
      - spark-network
    hostname: pyspark-container
    stdin_open: true
    tty: true
    volumes:
      - .:/workdir
      - shared-jars:/shared-jars

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invest
    volumes:
      - invest-pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - my-shared-network

  init-jars:
    image: debian:12
    container_name: init-jars
    command: >
      /bin/bash -c "
      apt-get update &&
      apt-get install -y curl &&
      curl -o /shared-jars/postgresql-42.6.0.jar https://jdbc.postgresql.org/download/postgresql-42.6.0.jar &&
      chmod -R 777 /shared-jars"
    volumes:
      - shared-jars:/shared-jars
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
  my-shared-network:
    driver: bridge

volumes:
  shared-jars:
  invest-pg-data:
    external: true
