import os

S3_BUCKET = os.environ["AWS_S3_BUCKET"]
S3_BRONZE_PATH = f"s3a://{S3_BUCKET}/bronze"
S3_SILVER_PATH = f"s3a://{S3_BUCKET}/silver"
S3_GOLD_PATH = f"s3a://{S3_BUCKET}/gold"

TICKERS = "tickers"
LAKEHOUSE_TICKERS_BRONZE_PATH = f"{S3_BRONZE_PATH}/{TICKERS}"
LAKEHOUSE_TICKERS_SILVER_PATH = f"{S3_SILVER_PATH}/{TICKERS}"
LAKEHOUSE_TICKERS_GOLD_PATH = f"{S3_GOLD_PATH}/{TICKERS}"

POSTGRES_TABLE_TICKERS = "invest.tickers"